### ISSUE TITLE
Nodemon error: undefined reference for user.room

### ISSUE THREAD

**Issue by CluelessWizard** [CluelessWizard/chat-app#2]
When I try to send a message the server returns an error which says user.room is undefined therefore it's crashed.

**Comment by CuriousWizard** [comment]
io.to(user.room).emit("message", { user: user.name, text: message });
               ^

TypeError: Cannot read property 'room' of undefined
    at Socket.<anonymous> (C:\Users\Brian\Documents\React\chat-app\server\index.js:46:16)    at Socket.emit (events.js:315:20)
    at C:\Users\Brian\Documents\React\chat-app\server\node_modules\socket.io\lib\socket.js:528:12
    at processTicksAndRejections (internal/process/task_queues.js:79:11)

**Comment by CuriousWizard** [comment]
The **_getUser()_** function didn't returned a user, because I used curly braces but no return, thus it was undefined.
After I checked that function in **_server/users.js_** and deleted braces, my chat is finally working.

Changes has been commited and push into master
